[package]
name = "rustls-aegis"
version = "0.1.0"
edition = "2024"

[dependencies]
rustls = "0.23.34"
aegis = "0.9"
sha2 = "0.10"
hmac = "0.12"

[dev-dependencies]
criterion = "0.7"
hex-literal = "1.1"
rcgen = "0.14"

[[bench]]
name = "ciphers"
harness = false
